add translate method
miaucl/bring-api pull request #10
Opened 2024-02-15 03:02 UTC by tr4nt0r

A first draft of a translate method. Still a lot to do, still has some hardcoded test data in it.
Downloading translation tables is missing, also i plan to get the corresponding locale for the lists from the userSettings.

2024-02-15 03:03 UTC, tr4nt0r commented on bring_api/bring.py
> +
is there a better and more efficient way to traverse the items in the BringItemsResponse?

2024-02-19 16:08 UTC, tr4nt0r commented
turns out the api endpoint i thought returned the language settings for all shopping lists does in fact not return all shopping lists. You have to explicitly set the language, otherwise the bring app uses the users default language setting, which is a totally different api endpoint. So I have added yet another method to communicate with the api.

2024-02-19 21:29 UTC, miaucl requested changes

2024-02-19 21:29 UTC, miaucl commented on bring_api/bring.py
> +        self.supported_locales = [
I would really put this list in a `const.py` file as well as the default `user_locale`.

2024-02-19 21:29 UTC, miaucl commented on bring_api/bring.py
> +                        for item in lst:  # type: ignore[attr-defined]
casting does not work here?

2024-02-19 21:29 UTC, miaucl commented on bring_api/bring.py
> +                item_id = self.__translations[locale].get(item_id, item_id)
Can be done as onliner: `item_id = self.__translations[locale].get(item_id, item_id) if to_locale else item_id = ({value: key for key, value in self.__translations[locale].items()}).get(item_id, item_id)`

2024-02-19 21:29 UTC, miaucl commented on bring_api/bring.py
> +                i["listUuid"]: {ii["key"]: ii["value"] for ii in i["usersettings"]}
Would put more informative var names instead of `i` and `ii`. I don't understand what it does^^

2024-02-19 21:29 UTC, miaucl commented on bring_api/types.py
> +class BringUserSettings(TypedDict):
if it is a single user setting, I would not use plural, but rather `BringUserSetting` or `BringUserSettingsEntry`

2024-02-19 21:29 UTC, miaucl commented on bring_api/types.py
> +class BringUserListSettings(TypedDict):
Same as for `BringUserSettings`

2024-02-20 21:38 UTC, miaucl commented on CHANGELOG.md
> +* **New API method:** sync_current_user ([tr4nt0r](https://github.com/tr4nt0r))
What does it?

2024-02-20 21:40 UTC, miaucl approved these changes
I trust in my test scripts that everything works fine :)

2024-02-20 22:40 UTC, merged